name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Install Curl and Node.js
      run: |
        echo "Installing curl and Node.js..."
        apk update
        apk add curl
        apk add nodejs npm
        node -v
        npm -v

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify Node.js Installation
      run: |
        node -v
        npm -v
        which node
        which npm

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Gitea Docker Registry
      uses: docker/login-action@v2
      with:
        registry: git.dreamfriday.com
        username: ${{ secrets.GITEAUSER }}
        password: ${{ secrets.GITEAPASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t git.dreamfriday.com/${{ secrets.GITEAUSER }}/payload:latest .
        docker push git.dreamfriday.com/${{ secrets.GITEAUSER }}/payload:latest
